### ISSUE TITLE
Concrete cms v9.1.3 compatibility

### ISSUE THREAD

**Issue by strandbein** [concrete5-community/empty_anchor#1]
Concrete cms v9.1.3 refuses the installation of this add-on. Would it be possible to update it?
Thx

**Comment by mlocati** [comment]
What do you mean with "refuses"? Do you see any error?

**Comment by strandbein** [comment]
Yes, see attachment.
<img width="1090" alt="Bildschirmfoto 2023-04-15 um 15 40 36" src="https://user-images.githubusercontent.com/3486633/232227636-9b75f114-cc10-4724-8de5-db2dc05f2bba.png">

**Comment by mlocati** [comment]
I've marked the package as compatible with ConcreteCMS v9: you should be able to install it now.

**Comment by strandbein** [comment]
Great, thank you!
